### ISSUE TITLE
Where can I get vidio data

### ISSUE THREAD

**Issue by Haodong-Yan** [lyn1874/memAE#2]
Where can I get vidio data

**Comment by lyn1874** [comment]
Hi, so the dataset is described at http://www.cse.cuhk.edu.hk/leojia/projects/detectabnormal/dataset.html. You could download it via `wget http://www.cse.cuhk.edu.hk/leojia/projects/detectabnormal/Avenue_Dataset.zip`

**Comment by Haodong-Yan** [comment]
Thanks,have a nice day!

**Comment by Haodong-Yan** [comment]
and I wonder if it is  necessary  to run requirement.sh? I want to run this code in windows , can I just run train.py and testing.py?

**Comment by lyn1874** [comment]
If your system has scikit-learn, opencv and tqdm, then there is no need to run requirement.sh. Otherwise, it will probably throw out an error such as `No module named ...`

**Comment by Haodong-Yan** [comment]
ok,thanks

**Comment by chenming1999** [comment]
How did you get this file? Avenue_gt.npy
